### ISSUE TITLE
Installation errors - Is the docker daemon running?

### ISSUE THREAD

**Issue by garysui** [pahud/lambda-layer-headless-chromium#4]
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
chmod: cannot access './layer/headless-chromium/headless-chromium': No such file or directory

I am novice and have no clue how to proceed from here

**Comment by pahud** [comment]
you need to install docker in your local environment before you can execute `build.sh`

https://github.com/pahud/lambda-layer-headless-chromium/blob/68cfb32c29578be20c48c9bd87992a0d3cd9d9b4/build.sh#L4-L6

An easy option is to launch a `Cloud9` IDE in AWS and it has everytihng you need for the development.

**Comment by garysui** [comment]
Thanks for the great tip!
